version: '3.9'

services:
  save-my-petrol:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: save-my-petrol
    restart: always
    ports:
      - "443:443"
    environment:
      APP_BASE_URL: ${APP_BASE_URL}
      MONGO_DB_URI: ${MONGO_DB_URI}
      MONGO_DATABASE: ${MONGO_DATABASE}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      KEY_STORE_PASSWORD: ${KEY_STORE_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - save-my-petrol-backend

  mongodb:
    # NOTE: Couldn't use the latest version of mongo in M2
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - save-my-petrol-backend-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    networks:
      - save-my-petrol-backend

volumes:
  save-my-petrol-backend-db:
    driver: local

networks:
  save-my-petrol-backend:
    driver: bridge
