server:
  address: 0.0.0.0
  port: ${APP_PORT:8080}

spring:
  codec:
    max-in-memory-size: 100MB

  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      database: ${MONGO_DATABASE}
      auto-index-creation: true

app:
  petrolStationsEndpoint: "https://sedeaplicaciones.minetur.gob.es/ServiciosRESTCarburantes/PreciosCarburantes/EstacionesTerrestres/"
