server:
  ssl:
    key-store: classpath:save-my-petrol.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: pkcs12
    key-alias: save-my-petrol
    key-password: ${KEY_STORE_PASSWORD}
  port: 443
  netty:
    max-initial-line-length: 100MB

spring:
  codec:
    max-in-memory-size: 100MB

  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      database: ${MONGO_DATABASE}
      auto-index-creation: true

logging:
  level:
    org:
      mongodb:
        driver:
          connection: WARN

app:
  baseUrl: ${APP_BASE_URL}
  petrolStationsEndpoint: "https://sedeaplicaciones.minetur.gob.es/ServiciosRESTCarburantes/PreciosCarburantes/EstacionesTerrestres/"
  stripe:
    apiKey: ${STRIPE_API_KEY}
    webhookSecret: ${STRIPE_WEBHOOK_SECRET}
