spring:
  codec:
    max-in-memory-size: 100MB

  data:
    mongodb:
      host: localhost
      port: ${MONGO_DB_PORT}
      username: ${MONGO_ROOT_USER}
      password: ${MONGO_ROOT_PASSWORD}
      database: ${MONGO_DATABASE}
      authentication-database: admin
      auto-index-creation: true

app:
  petrolStationsEndpoint: "https://sedeaplicaciones.minetur.gob.es/ServiciosRESTCarburantes/PreciosCarburantes/EstacionesTerrestres/"
