name: Build and deploy

on:
  workflow_dispatch:

jobs:
  build-artifact:
    name: build-artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn verify

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: save-my-petrol.jar
          path: target

  deploy-artifact:
    name: deploy-artifact
    runs-on: ubuntu-latest
    needs: build-artifact

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: save-my-petrol.jar
          path: target

      - name: Deploy to railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "save-my-petrol"